server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: edge-service
    
  config:
    import: optional:configserver:http://config-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: content-route-root
              uri: ${CONTENT_SERVICE_URL:http://content-manager}
              predicates:
                - Path=/topics

            - id: content-route-nested
              uri: ${CONTENT_SERVICE_URL:http://content-manager}
              predicates:
                - Path=/topics/**

            - id: progress-route-root
              uri: ${PROGRESS_SERVICE_URL:http://progress-manager}
              predicates:
                - Path=/progress

            - id: progress-route-nested
              uri: ${PROGRESS_SERVICE_URL:http://progress-manager}
              predicates:
                - Path=/progress/**